### ISSUE TITLE
manage.py: error: no such option: --format

### ISSUE THREAD

**Issue by rustanacexd** [Brobin/drf-generators#10]
I am using this `python manage.py generate api --format modelviewset` but it says `manage.py: error: no such option: --format`

**Comment by Brobin** [comment]
Are you sure you have the latest version (0.2.2) installed?

Try `pip install drf-generators==0.2.2`

**Comment by Brobin** [comment]
I was able to replicate this only in Python 2.7. Is this the version you are using?

**Comment by rustanacexd** [comment]
I am using python 3.3 and using the latest version of drf-generators 0.2.2, django version 1.7.7, drf version 3.1.1

**Comment by Brobin** [comment]
Alright, I found out it was an issue with optparse in Python < 3.4. Fixed as of 8a98e656288d43ee3ed897b29d9d5867dafe1f91. I'll have it uploaded to pypi asap.

Thanks for the bug report!

**Comment by rustanacexd** [comment]
works now thanks
