### ISSUE TITLE
final touch

### ISSUE THREAD

**Issue by ahmedjemmy** [Brobin/drf-generators#33]
that appeared after all what i have done

 Using the URLconf defined in example_api.urls, Django tried these URL patterns, in this order:

    ^admin/
    ^api/

The empty path didn't match any of these

**Comment by Brobin** [comment]
Can you please explain your problem in more detail? I don't understand what problem you are having.

**Comment by ahmedjemmy** [comment]
error 404 when running the project 
![screenshot from 2017-07-28 23-18-30](https://user-images.githubusercontent.com/16198541/28736637-1d8d1016-73eb-11e7-9bf4-bb070f4d88b8.png)

**Comment by Brobin** [comment]
You do not have a path for "/" defined.
