### ISSUE TITLE
Use drf-generators on an existing project?

### ISSUE THREAD

**Issue by cfortune** [Brobin/drf-generators#40]
Hello,  Pls have a look at the Turkle project at https://github.com/hltcoe/turkle/issues/32.  We're trying to add an api to it, but concerned that the generators will blow away existing files or otherwise radically change the underlying code design.  Your input would be very much appreciated.  Thanks in advance.

**Comment by Brobin** [comment]
If the files already exist (urls, views, etc.) they would overwrite existing code. It will warn you before overwriting. You could always run it and then merge back your existing stuff.
