### ISSUE TITLE
Generator only producing API View

### ISSUE THREAD

**Issue by sixsixtrample** [Brobin/drf-generators#41]
Using Django 2.2.2 and Python 3.7.3 the generator command will only create APIView views.py regardless of the command given. I tested this with an existing, a brand new, and another developer's venv, to the same result.

It does write a new file, but only APIView.

**Comment by adambain** [comment]
@sixsixtrample, not sure if you are still having this issue. I pulled this package down and ran into the same thing. Let me know if this is of use.
