### ISSUE TITLE
--format viewset not working

### ISSUE THREAD

**Issue by Jzeemo** [Brobin/drf-generators#43]
Hi, I am trying to generate views with `viewset `format but it always generates `apiview `format.

**Comment by silegon** [comment]
I have fix this bug

https://github.com/Brobin/drf-generators/pull/44/files

**Comment by DataGreed** [comment]
same problem for me, but trying to generate modelviewset.

The pull request by @silegon fixes the problem.

@Brobin I suggest merging it :)

**Comment by Brobin** [comment]
merged!
